import React from 'react'

function DesclaimerSection() {
  return (
    <div>
        <section className="text-gray-700 body-font">
            <div className="container px-5 py-24 mx-auto">
                <div className="flex flex-col text-center w-full mb-12">
                <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Disclaimer</h1>
                <p className="lg:w-2/3 mx-auto leading-relaxed text-base">
                    The information provided by MyAIBotix (“we,” “us,” or “our”) on our website and through our AI content generation tools is for general informational purposes only. All information provided is in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on our platform.
                </p>
                </div>
                <div className="lg:w-3/4 mx-auto">
                <div className="mb-6">
                    <h2 className="text-xl font-semibold mb-2">1. No Professional Advice</h2>
                    <p className="leading-relaxed text-base mb-2">
                    The content generated by MyAIBotix, including blog titles, social media tags, or other AI-generated content, should not be construed as professional, legal, or financial advice. Users are encouraged to consult a professional for specific advice tailored to their situation.
                    </p>
                </div>
                <div className="mb-6">
                    <h2 className="text-xl font-semibold mb-2">2. Use at Your Own Risk</h2>
                    <p className="leading-relaxed text-base mb-2">
                    You agree that your use of the content generated by MyAIBotix is at your sole risk. We do not guarantee that the content will meet your expectations or that it will be suitable for your specific purposes. MyAIBotix is not liable for any decisions or actions you take based on the content generated.
                    </p>
                </div>
                <div className="mb-6">
                    <h2 className="text-xl font-semibold mb-2">3. External Links Disclaimer</h2>
                    <p className="leading-relaxed text-base mb-2">
                    Our website may contain links to external websites. These links are provided for convenience only. MyAIBotix does not endorse or guarantee the accuracy of information on external sites, and we are not responsible for any content or privacy practices of those sites.
                    </p>
                </div>
                <div className="mb-6">
                    <h2 className="text-xl font-semibold mb-2">4. AI-Generated Content</h2>
                    <p className="leading-relaxed text-base mb-2">
                    The content generated by our AI tools is produced based on algorithms and pre-trained models. The accuracy or relevance of the generated content may vary depending on the data provided by the user. We do not guarantee the correctness or originality of the AI-generated content.
                    </p>
                </div>
                <div className="mb-6">
                    <h2 className="text-xl font-semibold mb-2">5. Changes to This Disclaimer</h2>
                    <p className="leading-relaxed text-base mb-2">
                    We may update this disclaimer from time to time. Any changes will be posted on this page, and we encourage you to review it regularly to stay informed of any updates.
                    </p>
                </div>
                <div className="mb-6">
                    <h2 className="text-xl font-semibold mb-2">6. Contact Us</h2>
                    <p className="leading-relaxed text-base">
                    If you have any questions regarding this disclaimer or your use of MyAIBotix, please contact us at:
                    </p>
                    <p className="leading-relaxed text-base">
                    <strong>Email:</strong> support@myaibotix.com<br />
                    <strong>Address:</strong> 123 AI Street, Silicon Valley, CA 94043
                    </p>
                </div>
                </div>
            </div>
        </section>               
    </div>
  )
}

export default DesclaimerSection